### ISSUE TITLE
Renaming file crashes Visual Studio

### ISSUE THREAD

**Issue by YevgenijZ** [devlooped/SmallSharp#15]
VS 16.8.5

SmallSharp 1.0.1

After renaming cs file using F2 in Solution Explorer Visual Studio crashes.

Rename one or two times, try to run.

![20210212_102653](https://user-images.githubusercontent.com/8945897/107745876-a682c800-6d1d-11eb-93b5-070cd9b81b7e.jpg)

**Comment by kzu** [comment]
This is not properly a crash, but just a `Debug.Fail` call inadvertently shipped because the package was built in debug mode 🤦 . 

Will ship an update without this momentarily.
